[project]
name = "easyvvuq"
description = "Library to facilitate simple Verification, Validation and Uncertainty Quantification of simulation codes"
readme = "README.md"
authors = [{name = "CCS"}]
version = "1.3.0.2"
license = {text = "LGPL-3.0-or-later OR GPL-3.0-or-later"}
requires-python = ">=3.10"

# Lean core required dependencies only
dependencies = [
    "numpy>=1.22",
    "scipy>=1.8",
    "pandas>=1.4",
    "chaospy>=4.3.2",
    "numpoly>=1.1.3",
    "dill",
    "cerberus",
]

[project.optional-dependencies]
dask = [
    "dask[complete]",
    "dask-jobqueue",
    "cloudpickle",
]
salib = [
    "SALib>=1.4.5",
]
ml = [
    "scikit-learn>=1.0",
]
all = [
    "easyvvuq[dask,salib,ml]",
]
tests = [
    "pytest>=7.0",
    "pytest-cov",
    "pytest-benchmark"
]

[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

lint = [
    "black",
    "ruff",
]

[project.urls]
Source = "https://github.com/UCL-CCS/EasyVVUQ"
Tracker = "https://github.com/UCL-CCS/EasyVVUQ/issues"
Documentation = "https://easyvvuq.readthedocs.io/en/dev/"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
write_to = "src/easyvvuq/_version.py"

[tool.black]
exclude = "src/easyvvuq/_version.py"

[tool.pytest.ini_options]
pep8ignore = [
    "*.py E265",
    "__init__.py E402",
    "tests/*.py E128",
]
pep8maxlinelength = 100

