# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Coveralls Generate

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        python -m pip install --editable .[tests]
        cd tests/cannonsim/src; make; cd ../../..
        pip install pytest-cov
        pip install coveralls
    - name: Create coverage report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pytest --benchmark-skip \
          --deselect=tests/test_dimension_adaptive_SC.py::test_results \
          --deselect=tests/test_pce_der_analysis.py::test_results \
          --deselect=tests/test_pce_der_analysis.py::test_results_vec \
          --deselect=tests/test_pce_der_analysis.py::test_results_vec_relative \
          --deselect=tests/test_pce_der_dep_analysis.py::test_results \
          --deselect=tests/test_pce_der_dep_analysis.py::test_results_vec \
          --deselect=tests/test_pce_der_dep_analysis.py::test_results_vec_relative \
          --deselect=tests/test_campaign.py::test_string \
          --deselect=tests/test_campaign.py::test_get_active_app \
          --deselect=tests/test_campaign.py::test_add_external_runs \
          --ignore=tests/test_SSC.py \
          --cov=. tests/
        coveralls --service=github
